export interface Session {
  id: string
  client: { name: string; avatar?: string; country: string }
  trainer: { name: string; avatar?: string; country: string }
  type: 'Monthly' | 'Free Trial' | 'One Time'
  scheduled: string
  duration: string
  amount: number
  clientConf: 'Yes' | 'Pending' | 'N/A'
  trainerConf: 'Yes' | 'Pending' | 'N/A'
  state: 'Completed' | 'Unconfirmed' | 'Scheduled' | 'Settled' | 'Disputed' | 'Missed'
}

export const DUMMY_SESSIONS: Session[] = [
  {
    id: 'S-0901',
    client: { name: 'Amara J.', avatar: 'https://i.pravatar.cc/150?u=1', country: 'US' },
    trainer: { name: 'Tunde B.', avatar: 'https://i.pravatar.cc/150?u=99', country: 'NG' },
    type: 'Monthly',
    scheduled: 'Today, 10:50AM',
    duration: '1.5hrs',
    amount: 20,
    clientConf: 'Yes',
    trainerConf: 'Yes',
    state: 'Completed',
  },
  {
    id: 'S-0900',
    client: { name: 'Cara K.', avatar: 'https://i.pravatar.cc/150?u=2', country: 'UK' },
    trainer: { name: 'Tunde B.', avatar: 'https://i.pravatar.cc/150?u=99', country: 'NG' },
    type: 'Monthly',
    scheduled: 'Today, 10:00AM',
    duration: '1hr',
    amount: 20,
    clientConf: 'Yes',
    trainerConf: 'Pending',
    state: 'Unconfirmed',
  },
  {
    id: 'S-0899',
    client: { name: 'Helen E.', avatar: 'https://i.pravatar.cc/150?u=3', country: 'US' },
    trainer: { name: 'Sam B.', avatar: 'https://i.pravatar.cc/150?u=88', country: 'NG' },
    type: 'Free Trial',
    scheduled: 'Today, 9:00AM',
    duration: '1hrs',
    amount: 0,
    clientConf: 'N/A',
    trainerConf: 'N/A',
    state: 'Scheduled',
  },
  {
    id: 'S-0898',
    client: { name: 'Dani K.', avatar: 'https://i.pravatar.cc/150?u=4', country: 'UK' },
    trainer: { name: 'Victor F.', avatar: 'https://i.pravatar.cc/150?u=77', country: 'NG' },
    type: 'One Time',
    scheduled: 'Yesterday, 11:45AM',
    duration: '2hrs',
    amount: 20,
    clientConf: 'Yes',
    trainerConf: 'Yes',
    state: 'Settled',
  },
  {
    id: 'S-0897',
    client: { name: 'Sally V.', avatar: 'https://i.pravatar.cc/150?u=5', country: 'US' },
    trainer: { name: 'Tunde B.', avatar: 'https://i.pravatar.cc/150?u=99', country: 'NG' },
    type: 'Monthly',
    scheduled: 'Yesterday, 11:00AM',
    duration: '1.5hrs',
    amount: 20,
    clientConf: 'Pending',
    trainerConf: 'Yes',
    state: 'Disputed',
  },
  {
    id: 'S-0896',
    client: { name: 'Jade K.', avatar: 'https://i.pravatar.cc/150?u=6', country: 'US' },
    trainer: { name: 'Sandy B.', avatar: 'https://i.pravatar.cc/150?u=66', country: 'NG' },
    type: 'Monthly',
    scheduled: 'May 1, 6:00PM',
    duration: '-',
    amount: 20,
    clientConf: 'Pending',
    trainerConf: 'Pending',
    state: 'Missed',
  },
  {
    id: 'S-0895',
    client: { name: 'Jade K.', avatar: 'https://i.pravatar.cc/150?u=6', country: 'US' },
    trainer: { name: 'Sandy B.', avatar: 'https://i.pravatar.cc/150?u=66', country: 'NG' },
    type: 'Monthly',
    scheduled: 'May 1, 8:00AM',
    duration: '1hr',
    amount: 20,
    clientConf: 'Pending',
    trainerConf: 'Pending',
    state: 'Unconfirmed',
  },
  {
    id: 'S-0894',
    client: { name: 'Jade K.', avatar: 'https://i.pravatar.cc/150?u=6', country: 'US' },
    trainer: { name: 'Sandy B.', avatar: 'https://i.pravatar.cc/150?u=66', country: 'NG' },
    type: 'One Time',
    scheduled: 'Apr 30, 2:00PM',
    duration: '1.5hrs',
    amount: 20,
    clientConf: 'Yes',
    trainerConf: 'Pending',
    state: 'Unconfirmed',
  },
  {
    id: 'S-0893',
    client: { name: 'Jade K.', avatar: 'https://i.pravatar.cc/150?u=6', country: 'US' },
    trainer: { name: 'Sandy B.', avatar: 'https://i.pravatar.cc/150?u=66', country: 'NG' },
    type: 'Monthly',
    scheduled: 'Apr 30, 9:00AM',
    duration: '-',
    amount: 20,
    clientConf: 'Pending',
    trainerConf: 'Yes',
    state: 'Disputed',
  },
  {
    id: 'S-0892',
    client: { name: 'Jade K.', avatar: 'https://i.pravatar.cc/150?u=6', country: 'US' },
    trainer: { name: 'Sandy B.', avatar: 'https://i.pravatar.cc/150?u=66', country: 'NG' },
    type: 'Monthly',
    scheduled: 'Apr 29, 9:00AM',
    duration: '-',
    amount: 20,
    clientConf: 'Pending',
    trainerConf: 'Pending',
    state: 'Missed',
  },
  {
    id: 'S-0891',
    client: { name: 'Jade K.', avatar: 'https://i.pravatar.cc/150?u=6', country: 'US' },
    trainer: { name: 'Sandy B.', avatar: 'https://i.pravatar.cc/150?u=66', country: 'NG' },
    type: 'Monthly',
    scheduled: 'Apr 28, 9:00AM',
    duration: '-',
    amount: 20,
    clientConf: 'Pending',
    trainerConf: 'Pending',
    state: 'Missed',
  }
]